nelmio_api_doc:
    documentation:
        openapi: 3.0.0
        info:
            title: Books API
            version: '1.0.0'
            description: API по спарсенным даннымо
    areas:
        path_patterns:
            - ^/api
